<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-28 at 22:12:26.
 */
$root = realpath($_SERVER["DOCUMENT_ROOT"]);
include "$root/app/controllers/BookstoreController.php";

class BookstoreControllerTest extends TestCase {

    /**
     * @var BookstoreController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BookstoreController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers BookstoreController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction() {
        // Remove the following lines when you implement this test.
        //$response = $this->object->action('GET', 'BookstoreController@index');
        $this->call('GET', '/bookstore/browse');
        $this->assertResponseOK();
    }

    /**
     * @covers BookstoreController::browseAction
     * @todo   Implement testBrowseAction().
     */
    public function testBrowseAction() {
        // Remove the following lines when you implement this test.
        $this->call('GET', '/bookstore/browse');
        $this->assertResponseOK();
    }

    /**
     * @covers BookstoreController::selectAction
     * @todo   Implement testSelectAction().
     */
    public function testSelectAction() {
        // Remove the following lines when you implement this test.
        $this->call('GET', '/bookstore/select/1');
        $this->assertResponseOK();
    }

    /**
     * @covers BookstoreController::searchAction
     * @todo   Implement testSearchAction().
     */
    public function testSearchAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BookstoreController::registerAction
     * @todo   Implement testRegisterAction().
     */
    public function testRegisterAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BookstoreController::loginAction
     * @todo   Implement testLoginAction().
     */
    public function testLoginAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BookstoreController::userAction
     * @todo   Implement testUserAction().
     */
    public function testUserAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BookstoreController::userchangeAction
     * @todo   Implement testUserchangeAction().
     */
    public function testUserchangeAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BookstoreController::logoutAction
     * @todo   Implement testLogoutAction().
     */
    public function testLogoutAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BookstoreController::rateAction
     * @todo   Implement testRateAction().
     */
    public function testRateAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BookstoreController::addCartAction
     * @todo   Implement testAddCartAction().
     */
    public function testAddCartAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BookstoreController::viewCartAction
     * @todo   Implement testViewCartAction().
     */
    public function testViewCartAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BookstoreController::checkRemoveCartAction
     * @todo   Implement testCheckRemoveCartAction().
     */
    public function testCheckRemoveCartAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BookstoreController::removeCartAction
     * @todo   Implement testRemoveCartAction().
     */
    public function testRemoveCartAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BookstoreController::checkoutAction
     * @todo   Implement testCheckoutAction().
     */
    public function testCheckoutAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BookstoreController::receiptAction
     * @todo   Implement testReceiptAction().
     */
    public function testReceiptAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
