<?php
$this->title = "Tickets";
$this->headTitle($this->title);
echo $this->loggedInAs();
?> 
<p><a href="<?php
    echo $this->url(array('controller' => 'request',
        'action' => 'add'));
    ?>">Add new request</a></p>
<table frame="box">
    <tr>
        <th>id</th>
        <th>date in</th>
        <th>originator</th>
        <th>assigned to</th>
        <th>subject</th>
        <th>description</th>
        <th>comments</th>
        <th>date out</th>
        <th>priority</th>
        <th>categories</th>
        <th>status</th>
        <th>&nbsp;</th>
    </tr>
    <?php
    $auth = Zend_Auth::getInstance();
    if (!$auth->hasIdentity()) {
        $this->_helper->redirector('index', 'index');
    }



    $accountTypeId = $auth->getIdentity()->account_type_id;
    $accountId = $auth->getIdentity()->id;
    $account = new Application_Model_DbTable_User();
    $status = new Application_Model_DbTable_Status();
    $priority = new Application_Model_DbTable_Priority();
    $category = new Application_Model_DbTable_Category();

    foreach ($this->request as $request) {

        if ($accountId == $request->originator_id || $accountTypeId == 1 || $accountId == $request->assigned_to_id) {
            ?>
            <tr>
                <td><?php echo $this->escape($request->id); ?></td>
                <td><?php echo $this->escape($request->date_in); ?></td>
                <td><?php echo $account->getId($this->escape($request->originator_id)); ?></td>
                <td><?php echo $account->getId($this->escape($request->assigned_to_id)); ?></td>
                <td><?php echo $this->escape($request->subject); ?></td>
                <td><?php echo $this->escape($request->description); ?></td>
                <td><?php echo $this->escape($request->comments); ?></td>
                <td><?php echo $this->escape($request->date_out); ?></td>
                <td><?php echo $priority->getPriorityId($this->escape($request->priority)); ?></td>          
                <td><?php echo $category->calcCategory($this->escape($request->category)); ?></td>
                <td><?php echo $status->getStatusId($this->escape($request->status_id)); ?></td>
                <td>
                    <?php
                    if (($request->status_id < 3 && $auth->getIdentity()->id == $request->originator_id) || ($auth->getIdentity()->account_type_id == 2 && $request->status_id < 3) || $auth->getIdentity()->account_type_id == 1) {
                        echo '<a href="' . $this->url(array('controller' => 'request', 'action' => 'edit', 'id' => $request->id)) . '">Edit</a> ';
                    }
                    if ($auth->getIdentity()->account_type_id == 1) {
                        echo '<a href="' . $this->url(array('controller' => 'request', 'action' => 'delete', 'id' => $request->id)) . '">Delete</a> ';
                    }
                    if ($request->status_id < 3 && $auth->getIdentity()->id == $request->originator_id && $auth->getIdentity()->account_type_id != 1) {
                        echo '<a href="' . $this->url(array('controller' => 'request', 'action' => 'cancel', 'id' => $request->id)) . '">Cancel</a>';
                    }
                    ?>
                </td>
            </tr>
            <?php
        }
    }
    ?>
</table>